src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=100, minMessage="Au minimum 3 caracteres")
     * @Assert\NotBlank(message="Cette formulaire est obligatoire")

     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, max=300, minMessage="Au minimum 10 caracteres")
     * @Assert\NotBlank(message="Cette formulaire est obligatoire")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     */
    private $user;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class,[
                'label' => 'Titre',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Titre de l\'article'
                ]
            ])
            ->add('description',TextareaType::class,[
                'label' => 'Description',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Description de l\'article'
                    ]
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use App\Form\Handler\PostFormHandler;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/blog", name="post_")
 */
class PostController extends AbstractController
{
    protected $entityManagerInterface;
    protected $repository;
    public function __construct(EntityManagerInterface $entityManagerInterface, PostRepository $repository)
    {
        $this->entityManagerInterface = $entityManagerInterface;
        $this->repository = $repository;
    }

    /**
     * @Route("/lists", name="lists")
     */
    public function index(){
        return $this->render('post/index.html.twig', [
            'posts' => $this->repository->findAll(),
        ]);
    }
    
    /**
     * @Route("/new", name="new")
     */
    public function new(Request $request, Security $security): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $formHandler = new PostFormHandler($form, $request, $this->entityManagerInterface, $security);

        if (!is_null($formHandler->process())) {
            $this->addFlash('success','Création article ok');
            return $this->redirectToRoute('home');
        }
        return $this->render('post/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function update(Request $request, Post $post, Security $security)
    {
        $form = $this->createForm(PostType::class, $post);
        $formHandler = new PostFormHandler($form, $request, $this->entityManagerInterface, $security);

        if (!is_null($formHandler->process())) {
            $this->addFlash('success','Modifiction ok');
            return $this->redirectToRoute('post_lists');
        }

        return $this->render('post/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/post/edit.html.twig
 {% extends 'base.html.twig' %}

{% block title %}Modification!{% endblock %}

{% block body %}
    <main role="main">
        <div class="jumbotron">
            <div class="container text-center">
            <h1>Modification</h1>
            </div>
        </div>

        <div class="container">
                <div class="card shadow">
                    <div class="card-body">
                        {{ include('post/form.html.twig')}} 
                    </div>
                </div>
        </div>
        <!-- /container -->
    </main>
{% endblock %}

templates/post/form.html.twig
{{ form_start(form) }}
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="form-group">                                   
                    {{form_row(form.title)}}                                   
                </div>
                <div class="form-group">                                   
                    {{form_row(form.description)}}                                   
                </div>
            </div>
        </div>
        <div class="row text-right">
            <button type="subtmit" class="btn btn-info btn-sm">Enregistrer</button> |
            <a href="{{ path('home') }}" class="btn btn-secondary btn-sm">Annuler</a>
        </div>
{{ form_end(form) }}

templates/post/index.html.twig
 {% extends 'base.html.twig' %}

{% block title %}List Articles!{% endblock %}

{% block body %}
    <main role="main">
        <div class="jumbotron">
            <div class="container text-center">
            <h1>List articles</h1>
            </div>
        </div>
     
        <div class="container">

                {% for message in app.flashes('success')%}
                        <div class="alert alert-success text-center">{{message}}</div>
                {% endfor %}
                <table class="table table-striped">
                     <thead>
                        <tr>
                            <th>Titre</th>
                            <th>Auteur</th>
                            <th>Description</th>
                            <th>Date Publication</th>
                            <th>Date Modification</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td>{{ post.title }}</td>
                                <td>{{ post.user.username }}</td>
                                <td>{{ post.description }}</td>
                                <td>{{ post.createdAt | date('d-m-y') }}</td>
                                <td>{{ post.updatedAt | date('d-m-y') }}</td>
                                <td>
                                    <a class="btn btn-warning" href="{{ path('post_edit', {id:post.id}) }}" role="button">Modifier</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                    
        </div>
        </div>
        <!-- /container -->
    </main>
{% endblock %}

templates/post/new.html.twig
 {% extends 'base.html.twig' %}

{% block title %}Nouveau!{% endblock %}

{% block body %}
    <main role="main">
        <div class="jumbotron">
            <div class="container text-center">
            <h1>Création article</h1>
            </div>
        </div>

        <div class="container">
                <div class="card shadow">
                    <div class="card-body">
                        {{ include('post/form.html.twig')}} 
                    </div>
                </div>
        </div>
        <!-- /container -->
    </main>
{% endblock %}